### ISSUE TITLE
Localize category names

### ISSUE THREAD

**Issue by dreamforceinc** [oiad/ZSC#17]
https://github.com/oiad/ZSC/blob/ace4d91425e5163ada187333864569a8c32e1a0c/scripts/traders/server_traders.sqf#L9
How about changing category names to localized versions?
i.e. "Ammunition" to (localize "STR_CL_AT_CATEGORY_AMMUNITION"), and of course add it to stringTable.xml?

**Comment by oiad** [comment]
This is a pretty good idea, I'd probably do it for epoch and port it to here though, I'll get onto it when I have some time, cheers!

**Comment by dreamforceinc** [comment]
I have already done this for my server.  :) except owerpoch.

**Comment by dreamforceinc** [comment]
Why hero trader have a "Clothes" category name and bandit trader have a "Clothing" category name? They are used different category IDs, so can I use same names for both traders?

Why "Profiteer4", "Worker3" use same category names "Trucks" but "UN_CDF_Soldier_Pilot_EP1" use "Trucks Unarmed" name? They are use different IDs but same items.
