### ISSUE TITLE
Giving NEW players coins on their first login:

### ISSUE THREAD

**Issue by ghost** [oiad/ZSC#5]
if (_newPlayer) then {_bankCoins = 5000};
Did not work for me. Missing ;

if (_newPlayer) then {_bankCoins = 5000;};
Worked.

**Comment by ghost** [comment]
Well, theoretically there is nothing wrong with default code, but I have to agree with @ch0c  and confirm this - same strange experience here - adding ';' solved problem as I remember from ZSC installatation.

**Comment by oiad** [comment]
I cant recall this giving me a problem but I'll make the change regardless
Cheers for the heads up! Appreciate it
