### ISSUE TITLE
Safe Money Doesnt Safe

### ISSUE THREAD

**Issue by MollyXVI** [oiad/ZSC#9]
Money u put into ur safe doesn't save after restart.

**Comment by oiad** [comment]
I bet it does.

**Comment by MollyXVI** [comment]
no, it doesn't for me

**Comment by ReDBaroN1** [comment]
does for me...

**Comment by MollyXVI** [comment]
i must have done something wrong then, any ideas?

**Comment by oiad** [comment]
None at all, you've provided nothing apart from a vague statement saying "it doesn't work"
Please provide your server RPT and your client RPT

**Comment by MollyXVI** [comment]
https://paste.md-5.net/nefoqonuna.tex
